<a href="https://colab.research.google.com/github/jeffheaton/app_deep_learning/blob/main/t81_558_class_06_4_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="In Colab öffnen"/></a>


# T81-558: Anwendungen tiefer neuronaler Netzwerke
**Modul 11: Natürliche Sprachverarbeitung und Spracherkennung**
* Dozent: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Jeff Heaton](https://sites.wustl.edu/jeffheaton/)
* Weitere Informationen finden Sie unter [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Modul 6 Material

* Teil 6.1: Einführung in Transformatoren [[Video]](https://www.youtube.com/watch?v=mn6r5PYJcu0&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Video]](https://www.youtube.com/watch?v=mn6r5PYJcu0&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN)
* Teil 6.2: Zugriff auf die ChatGPT-API [[Video]](https://www.youtube.com/watch?v=tcdscXl4o5w&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Video]](https://www.youtube.com/watch?v=tcdscXl4o5w&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN)
* Teil 6.3: LLM-Speicher [[Video]](https://www.youtube.com/watch?v=oGQ3TQx1Qs8&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Video]](https://www.youtube.com/watch?v=oGQ3TQx1Qs8&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN)
* **Teil 6.4: Einführung in Einbettungen** [[Video]](https://www.youtube.com/watch?v=e6kcs9Uj_ps&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Video]](https://www.youtube.com/watch?v=e6kcs9Uj_ps&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN)
* Teil 6.5: Prompt Engineering [[Video]](https://www.youtube.com/watch?v=miTpIDR7k6c&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Video]](https://www.youtube.com/watch?v=miTpIDR7k6c&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN)

# Google CoLab-Anweisungen

Der folgende Code stellt sicher, dass Google CoLab die richtige Version von TensorFlow ausführt.

In [1]:
try:
    from google.colab import drive

    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: not using Google CoLab


# Teil 6.4: Was sind Embedding-Layer in PyTorch

[Embedding Layers](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html) sind eine praktische Funktion von PyTorch, mit der das Programm automatisch zusätzliche Informationen in den Datenfluss Ihres neuronalen Netzwerks einfügen kann. Eine Einbettungsebene würde es Ihnen automatisch ermöglichen, Vektoren anstelle von Wortindizes einzufügen.

Programmierer verwenden häufig Einbettungsebenen mit Natural Language Processing (NLP); Sie können diese Ebenen jedoch auch verwenden, wenn Sie einen längeren Vektor an einer Indexwertstelle einfügen möchten. In gewisser Weise können Sie sich eine Einbettungsebene als Dimensionserweiterung vorstellen. Die Hoffnung ist jedoch, dass diese zusätzlichen Dimensionen dem Modell mehr Informationen liefern und zu einem besseren Ergebnis führen.

## Einfaches Beispiel für eine Einbettungsebene

* **num_embeddings** = Wie groß ist das Vokabular? Wie viele Kategorien kodieren Sie? Dieser Parameter ist die Anzahl der Elemente in Ihrer „Nachschlagetabelle“.
* **embedding_dim** = Wie viele Zahlen im Vektor Sie zurückgeben möchten.

Nun erstellen wir ein neuronales Netzwerk mit einem Vokabular von 10, das diese Werte zwischen 0 und 9 auf 4 Zahlenvektoren reduziert. Dieses neuronale Netzwerk tut nichts anderes, als die Einbettung an die Ausgabe weiterzuleiten. Aber es lässt uns sehen, was die Einbettung macht. Jeder eingehende Merkmalsvektor wird zwei solcher Merkmale haben.

In [2]:
import torch
import torch.nn as nn

embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=4)
optimizer = torch.optim.Adam(embedding_layer.parameters(), lr=0.001)
loss_function = nn.MSELoss()

Werfen wir einen Blick auf die Struktur dieses neuronalen Netzwerks, um zu sehen, was darin passiert.

In [3]:
print(embedding_layer)

Embedding(10, 4)


Für dieses neuronale Netzwerk, das nur eine Einbettungsschicht ist, ist die Eingabe ein Vektor der Größe 2. Diese beiden Eingaben sind Ganzzahlen von 0 bis 9 (entsprechend der angeforderten Eingabedim-Menge von 10 Werten). Wenn wir uns die Zusammenfassung oben ansehen, sehen wir, dass die Einbettungsschicht 40 Parameter hat. Dieser Wert stammt aus der eingebetteten Nachschlagetabelle, die vier Beträge (Ausgabedim) für jeden der 10 (Eingabedim) möglichen Ganzzahlwerte für die beiden Eingaben enthält. Die Ausgabe besteht aus 2 (Eingabelänge) Vektoren der Länge 4 (Ausgabedim), was zu einer Gesamtausgabegröße von 8 führt, was der Ausgabeform entspricht, die in der Zusammenfassung oben angegeben ist.

Lassen Sie uns nun das neuronale Netzwerk mit zwei Zeilen abfragen. Die Eingabe sind zwei ganzzahlige Werte, wie bei der Erstellung des neuronalen Netzwerks angegeben.

In [4]:
input_tensor = torch.tensor([[1, 2]], dtype=torch.long)
pred = embedding_layer(input_tensor)

print(input_tensor.shape)
print(pred)

torch.Size([1, 2])
tensor([[[ 0.1541,  0.5140,  1.0844, -0.4065],
         [ 1.3428, -2.2125, -0.8158, -1.7568]]], grad_fn=<EmbeddingBackward0>)


Hier sehen wir zwei Vektoren der Länge 4, die PyTorch für jede Eingabe-Ganzzahl nachgeschlagen hat. Denken Sie daran, dass Python-Arrays nullbasiert sind. PyTorch hat den Wert 1 durch die zweite Zeile der 10 x 4-Nachschlagematrix ersetzt. In ähnlicher Weise hat PyTorch den Wert 2 durch die dritte Zeile der Nachschlagematrix zurückgegeben. Der folgende Code zeigt die Nachschlagematrix in ihrer Gesamtheit an. Die Einbettungsebene führt keine mathematischen Operationen aus, außer das Einfügen der richtigen Zeile aus der Nachschlagetabelle.

In [5]:
embedding_layer.weight.data

tensor([[ 1.6017e-03,  4.9949e-01, -6.1325e-01,  5.3117e-01],
        [ 1.5415e-01,  5.1404e-01,  1.0844e+00, -4.0654e-01],
        [ 1.3428e+00, -2.2125e+00, -8.1585e-01, -1.7568e+00],
        [-1.3535e+00,  9.9905e-01,  3.0198e-01,  2.0349e+00],
        [ 4.8691e-01, -1.2690e+00, -1.2903e-01, -7.8702e-01],
        [-2.1178e+00, -1.4623e+00,  1.0718e-01, -5.1232e-01],
        [-1.3009e+00,  7.6286e-02, -3.6805e+00,  1.0944e+00],
        [-1.2939e+00, -2.3363e-01,  8.1395e-01,  9.0485e-01],
        [ 8.2642e-01, -5.8817e-01,  9.4454e-01, -1.7300e+00],
        [-6.7173e-01,  1.1404e+00, -1.1704e-01,  2.9404e-02]])

Die oben genannten Werte sind Zufallsparameter, die PyTorch als Ausgangspunkte generiert hat. Im Allgemeinen werden wir eine Einbettung übertragen oder diese Zufallswerte in etwas Nützliches trainieren. Der folgende Abschnitt zeigt, wie eine handcodierte Einbettung eingebettet wird.

## Eine Einbettung übertragen

Jetzt sehen wir, wie man eine Embedding-Suche fest codiert, die eine einfache One-Hot-Kodierung durchführt. One-Hot-Kodierung würde die Eingabe-Integerwerte 0, 1 und 2 in die Vektoren $[1,0,0]$, $[0,1,0]$ bzw. $[0,0,1]$ umwandeln. Der folgende Code ersetzt die zufälligen Suchwerte in der Embedding-Schicht durch diese von One-Hot-Kodierung inspirierte Suchtabelle.

In [6]:
import torch
import torch.nn as nn

# Definieren der eingebetteten Nachschlagematrix
embedding_lookup = torch.tensor(
    [[1, 0, 0], [0, 1, 0], [0, 0, 1]], dtype=torch.float32
)  # Stellen Sie sicher, dass Sie float32 für Gewichtsmatrizen verwenden

# Erstellen Sie die Einbettungsebene
embedding_layer = nn.Embedding(num_embeddings=3, embedding_dim=3)

# Legen Sie die Gewichte der Einbettungsebene fest
embedding_layer.weight.data = embedding_lookup

Wir haben die folgenden Parameter für die Embedding-Ebene:

* input_dim=3 – Es sind drei verschiedene ganzzahlige kategorische Werte zulässig.
* output_dim=3 – Drei Spalten stellen einen kategorischen Wert mit drei möglichen Werten pro One-Hot-Kodierung dar.
* input_length=2 – Der Eingabevektor hat zwei dieser kategorischen Werte.

Wir fragen das neuronale Netzwerk mit zwei kategorischen Werten ab, um die durchgeführte Suche anzuzeigen.

In [7]:
# Erstellen Sie den Eingabetensor direkt in PyTorch
input_tensor = torch.tensor([[0, 1]], dtype=torch.long)

# Vorwärtspass, um die Vorhersagen zu erhalten
pred = embedding_layer(input_tensor)

print(input_tensor.shape)
print(pred)

torch.Size([1, 2])
tensor([[[1., 0., 0.],
         [0., 1., 0.]]], grad_fn=<EmbeddingBackward0>)


Die angegebene Ausgabe zeigt, dass wir dem Programm zwei Zeilen aus der One-Hot-Kodierungstabelle bereitgestellt haben. Diese Kodierung ist eine korrekte One-Hot-Kodierung für die Werte 0 und 1, wobei bis zu 3 eindeutige Werte möglich sind.

Der folgende Abschnitt zeigt, wie diese eingebettete Nachschlagetabelle trainiert wird.

## Training einer Einbettung

Zunächst machen wir von den folgenden Importen Gebrauch.

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import OneHotcoder
from torch.nn.utils.rnn import pad_sequence

Wir erstellen ein neuronales Netzwerk, das Restaurantbewertungen nach positiv oder negativ klassifiziert. Dieses neuronale Netzwerk kann Zeichenfolgen als Eingabe akzeptieren, wie hier angegeben. Dieser Code enthält auch positive oder negative Beschriftungen für jede Bewertung.

In [9]:
# Definieren Sie 10 Restaurantbewertungen.
reviews = [
    "Never coming back!",
    "Horrible service",
    "Rude waitress",
    "Cold food.",
    "Horrible food!",
    "Awesome",
    "Awesome service!",
    "Rocks!",
    "poor work",
    "Couldn't have done better",
]

# Beschriftungen definieren (1=negativ, 0=positiv)
labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

Beachten Sie, dass die vorletzte Beschriftung falsch ist. Fehler wie dieser sind nicht allzu ungewöhnlich, da die meisten Trainingsdaten etwas Rauschen aufweisen können.

Wir definieren eine Vokabulargröße von 50 Wörtern. Obwohl wir nicht 50 Wörter haben, ist es in Ordnung, einen größeren Wert als nötig zu verwenden. Wenn mehr als 50 Wörter vorhanden sind, werden die am wenigsten häufig verwendeten Wörter im Trainingssatz während des Trainings automatisch von der Einbettungsschicht gelöscht. Für die Eingabe kodieren wir die Zeichenfolgen One-Hot. Wir verwenden hier die One-Hot-Kodierungsmethode von TensorFlow anstelle von Scikit-Learn. Scikit-learn würde diese Zeichenfolgen in die Nullen und Einsen erweitern, wie wir es normalerweise bei Dummyvariablen sehen würden. TensorFlow übersetzt alle Wörter in Indexwerte und ersetzt jedes Wort durch diesen Index.

In [10]:
# One-Hot-Encode-Bewertungen
VOCAB_SIZE = 50
encoded_reviews = [
    torch.tensor([hash(word) % VOCAB_SIZE for word in review.split()])
    for review in reviews
]

print(f"Verschlüsselte Bewertungen: {encoded_reviews}")

Encoded reviews: [tensor([16, 18, 25]), tensor([37,  7]), tensor([24, 28]), tensor([42,  5]), tensor([37, 21]), tensor([36]), tensor([36, 42]), tensor([2]), tensor([42, 38]), tensor([19,  4, 15,  6])]


Das Programm kodiert diese Rezensionen in Wortindizes, ihre Längen sind jedoch unterschiedlich. Wir füllen diese Rezensionen auf 4 Wörter auf und kürzen alle Wörter nach dem vierten Wort.

In [11]:
MAX_LENGTH = 4
padded_reviews = pad_sequence(
    encoded_reviews, batch_first=True, padding_value=0
).narrow(1, 0, MAX_LENGTH)
print(padded_reviews)

tensor([[16, 18, 25,  0],
        [37,  7,  0,  0],
        [24, 28,  0,  0],
        [42,  5,  0,  0],
        [37, 21,  0,  0],
        [36,  0,  0,  0],
        [36, 42,  0,  0],
        [ 2,  0,  0,  0],
        [42, 38,  0,  0],
        [19,  4, 15,  6]])


Wie in der Einstellung **padding=post** angegeben, wird jede Rezension durch Anhängen von Nullen am Ende aufgefüllt, wie in der Einstellung **padding=post** angegeben.

Als Nächstes erstellen wir ein neuronales Netzwerk, um das Klassifizieren dieser Bewertungen zu lernen.

In [12]:
model = nn.Sequential(
    nn.Embedding(VOCAB_SIZE, 8),
    nn.Flatten(),
    nn.Linear(8 * MAX_LENGTH, 1),
    nn.Sigmoid(),
)

Dieses Netzwerk akzeptiert vier ganzzahlige Eingaben, die die Indizes einer gepolsterten Filmkritik angeben. Die erste Einbettungsschicht konvertiert diese vier Indizes in vier Vektoren der Länge 8. Diese Vektoren stammen aus der Nachschlagetabelle, die 50 (VOCAB_SIZE) Zeilen mit Vektoren der Länge 8 enthält. Diese Kodierung ist an den 400 (8 mal 50) Parametern in der Einbettungsschicht erkennbar. Die Ausgabegröße der Einbettungsschicht beträgt 32 (4 Wörter ausgedrückt als 8-stellige eingebettete Vektoren). Ein einzelnes Ausgabeneuron ist durch 33 Gewichte (32 aus der Einbettungsschicht und ein einzelnes Bias-Neuron) mit der Einbettungsschicht verbunden. Da dies ein Einklassenklassifizierungsnetzwerk ist, verwenden wir die Sigmoid-Aktivierungsfunktion und binary_crossentropy.

Das Programm trainiert nun das neuronale Netzwerk. Die Einbettungssuche und die dichten 33-Gewichte werden aktualisiert, um ein besseres Ergebnis zu erzielen.

In [14]:
criterion = nn.BCELoss()  # Binäre Kreuzentropie
optimizer = optim.Adam(model.parameters())

# Trainieren des Modells
epochs = 100
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(padded_reviews.long())
    loss = criterion(outputs.squeeze(), torch.tensor(labels, dtype=torch.float))
    loss.backward()
    optimizer.step()

Wir können die gelernten Einbettungen sehen. Stellen Sie sich den Vektor jedes Wortes als einen Ort im 8-dimensionalen Raum vor, an dem Wörter, die mit positiven Bewertungen verbunden sind, nahe bei anderen Wörtern liegen. In ähnlicher Weise platziert das Training negative Bewertungen nahe beieinander. Zusätzlich zum Training, das diese Einbettungen festlegt, lernen die 33 Gewichte zwischen der Einbettungsschicht und dem Ausgabeneuron auf ähnliche Weise, diese Einbettungen in eine tatsächliche Vorhersage umzuwandeln. Sie können diese Einbettungen hier sehen.

In [16]:
embedding_weights = list(model[0].parameters())[0]
print(embedding_weights.shape)
print(embedding_weights)

torch.Size([50, 8])
Parameter containing:
tensor([[-6.6702e-01,  7.9332e-01,  1.4016e+00, -4.5947e-01, -6.4406e-01,
         -4.1454e-01, -1.0128e+00,  6.8736e-01],
        [ 5.0813e-01,  1.5599e+00, -1.1821e-01,  4.0191e-01, -1.4427e-01,
          4.3327e-01,  7.3892e-01,  7.8627e-01],
        [-1.4003e+00,  1.1563e+00, -6.7240e-02, -1.9336e+00,  2.6581e-01,
         -1.0005e+00,  1.7278e+00,  7.4226e-01],
        [ 1.5777e+00, -5.7344e-01, -6.9826e-01, -4.1497e-01,  3.2424e-01,
          9.6881e-01,  4.2793e-01,  1.2810e+00],
        [ 1.9169e-01,  2.5659e-01, -1.0394e+00, -4.2579e-01, -4.9159e-01,
          2.6051e-01,  1.2269e-01,  3.4496e-02],
        [ 1.1741e+00,  6.4354e-01, -8.8106e-01, -1.8514e+00, -8.2117e-01,
          1.3525e-01,  5.6363e-01,  3.2708e+00],
        [ 8.8823e-01, -7.7813e-01,  1.1075e+00, -2.7059e-01,  1.2459e-01,
          6.8583e-01, -1.4626e+00, -5.6774e-01],
        [-1.0156e+00, -8.9942e-01, -7.3420e-01,  1.8556e+00, -2.2097e+00,
         -2.2803e-01,  

Wir können jetzt die Genauigkeit dieses neuronalen Netzwerks bewerten, einschließlich der Einbettungen und der erlernten dichten Schicht.

In [17]:
# Auswertung
with torch.no_grad():
    outputs = model(padded_reviews.long())
    predictions = (outputs > 0.5).float().squeeze()
    accuracy = (predictions == torch.tensor(labels)).float().mean().item()
    loss_value = criterion(
        outputs.squeeze(), torch.tensor(labels, dtype=torch.float)
    ).item()

print(f"Genauigkeit: {accuracy}")
print(f"Log-Verlust: {Verlustwert}")

Accuracy: 0.8999999761581421
Log-loss: 0.4487539827823639


Die Genauigkeit ist großartig, aber es könnte zu Überanpassung kommen. Bei einem komplexeren Datensatz wäre es gut, frühzeitig zu stoppen, um eine Überanpassung zu vermeiden. Der Verlust ist jedoch nicht perfekt. Obwohl die vorhergesagten Wahrscheinlichkeiten in jedem Fall eine korrekte Vorhersage anzeigten, erreichte das Programm nicht absolutes Vertrauen in jede richtige Antwort. Der Mangel an Vertrauen war wahrscheinlich auf die geringe Menge an Rauschen (wie zuvor besprochen) im Datensatz zurückzuführen. Einige Wörter, die sowohl in positiven als auch in negativen Bewertungen auftauchten, trugen zu diesem Mangel an absoluter Sicherheit bei.